version: '3'
services:
  sovanthornimage:
    container_name: thorn-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3288:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - data_analytics

networks:
  data_analytics:
    external: true
